/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html-logo-3d-model-ab8b32cab3364027ab00a033a0b2ff38
Title: HTML logo 3d model
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import BootstrapScene from "../3d models/bootstrap.glb"
import gsap from "gsap";
const Bootstrap = (props) => {
    const { nodes, materials } = useGLTF(BootstrapScene);
    const BootstrapRef = useRef()
    useEffect(() => {
        const timeline = gsap.timeline();
        timeline.to(BootstrapRef.current.rotation, {
            y: 360, repeat: -1, duration: 250,ease:"linear"
        })
    }, [])

    return (
        <group {...props} dispose={null} ref={BootstrapRef}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials["Material.006"]}
          position={[1.493, 0.288, 0.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[-0.652, -0.285, 0.356]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.25}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text001.geometry}
          material={nodes.Text001.material}
          position={[-1.86, -1.687, 0.263]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    );
}

export default Bootstrap