/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html-logo-3d-model-ab8b32cab3364027ab00a033a0b2ff38
Title: HTML logo 3d model
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import GsapScene from "../3d models/gsap.glb"
import * as THREE from 'three';
import gsap from "gsap";
const Gsap = (props) => {
    const { nodes, materials } = useGLTF(GsapScene);
    const GsapRef = useRef()



    return (
      <group {...props} dispose={null} ref={GsapRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials["SVGMat.166"]}
        position={[-11.523, -1.529, -0.433]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={materials["SVGMat.167"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve004.geometry}
        material={materials["SVGMat.168"]}
        position={[-11.019, -1.565, -0.401]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005.geometry}
        material={materials["SVGMat.169"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve006.geometry}
        material={materials["SVGMat.169"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007.geometry}
        material={materials["SVGMat.169"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve008.geometry}
        material={materials["SVGMat.169"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve009.geometry}
        material={materials["SVGMat.170"]}
        position={[-11.019, -1.565, -0.275]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve010.geometry}
        material={materials["SVGMat.171"]}
        position={[-11.019, -1.565, -0.405]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve011.geometry}
        material={materials["SVGMat.172"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve012.geometry}
        material={materials["SVGMat.173"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve013.geometry}
        material={materials["SVGMat.174"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve014.geometry}
        material={materials["SVGMat.175"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve015.geometry}
        material={materials["SVGMat.176"]}
        position={[-11.019, -1.565, -0.286]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve016.geometry}
        material={materials["SVGMat.177"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve017.geometry}
        material={materials["SVGMat.178"]}
        position={[-11.019, -1.565, -0.254]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve018.geometry}
        material={materials["SVGMat.179"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve019.geometry}
        material={materials["SVGMat.180"]}
        position={[-11.019, -1.565, -0.261]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve020.geometry}
        material={materials["SVGMat.181"]}
        position={[-11.019, -1.565, -0.426]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve021.geometry}
        material={materials["SVGMat.181"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve022.geometry}
        material={materials["SVGMat.182"]}
        position={[-11.019, -1.565, -0.282]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve023.geometry}
        material={materials["SVGMat.183"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve024.geometry}
        material={materials["SVGMat.184"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve025.geometry}
        material={materials["SVGMat.185"]}
        position={[-11.019, -1.565, -0.397]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve026.geometry}
        material={materials["SVGMat.186"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve027.geometry}
        material={materials["SVGMat.187"]}
        position={[-11.019, -1.565, -0.283]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve028.geometry}
        material={materials["SVGMat.188"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve031.geometry}
        material={materials["SVGMat.189"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve032.geometry}
        material={materials["SVGMat.190"]}
        position={[-11.019, -1.565, -0.255]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve033.geometry}
        material={materials["SVGMat.191"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve034.geometry}
        material={materials["SVGMat.192"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve037.geometry}
        material={materials["SVGMat.193"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve038.geometry}
        material={materials["SVGMat.194"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve039.geometry}
        material={materials["SVGMat.195"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve041.geometry}
        material={materials["SVGMat.196"]}
        position={[-11.019, -1.565, -0.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={8.42}
      />
      <group
        position={[-2.15, -0.708, -0.34]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-93.673}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve301.geometry}
          material={materials["SVGMat.165"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve301_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
    </group>
    );
}

export default Gsap