/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Erik Egnatosyan (https://sketchfab.com/sans.egnatosyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/html-logo-3d-model-ab8b32cab3364027ab00a033a0b2ff38
Title: HTML logo 3d model
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import jsScene from "../3d models/js.glb"
import gsap from "gsap";
const Js = (props) => {
    const { nodes, materials } = useGLTF(jsScene);
    const JsRef = useRef()
    useEffect(() => {
        const timeline = gsap.timeline();
        timeline.to(JsRef.current.rotation, {
            y: -360, repeat: -1, duration: 250, ease: "linear"
        })
    }, [])

    return (
        <group {...props} dispose={null} ref={JsRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.004"]}
        position={[-0.016, 1.405, 0]}
        scale={[1.688, 1, 0.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-1.24, -0.266, 0.324]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.367, 1.083, 3.966]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.005"]}
        position={[-1.789, -2.028, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
    );
}

export default Js